const actiontypes = {
  SET_USER: 'SET_USER',
  SET_TOKEN: 'SET_TOKEN',
  SET_LOADINGSHOW: 'SET_LOADINGSHOW',
  SET_PROJECTS:'SET_PROJECTS',
  SET_PROJECT:'SET_PROJECT',
  SET_PROJECT_EDITTYPE: 'SET_PROJECT_EDITTYPE',
  SET_PROJECTINFO_SHOW:'SET_PROJECTINFO_SHOW',
  SET_CURRENT_PARAGRAPHID:'SET_CURRENT_PARAGRAPHID',
  SET_CURRENT_OPTIONID:'SET_CURRENT_OPTIONID'
}

export default actiontypes;