const actiontypes = {
  TO_LOGIN: 'TO_LOGIN',
  SET_PROJECTS:'SET_PROJECTS',
  SET_PROJECT:'SET_PROJECT',
  SET_PROJECT_EDITTYPE: 'SET_PROJECT_EDITTYPE',
  SET_PROJECTINFO_SHOW:'SET_PROJECTINFO_SHOW',
  SET_CURRENT_PARAGRAPHID:'SET_CURRENT_PARAGRAPHID',
  SET_CURRENT_OPTIONID:'SET_CURRENT_OPTIONID'
}

export default actiontypes;